package Visao;

import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import Controle.ControleFornecedor;
import Controle.ControleNota_entrada;
import java.sql.Date;
import Controle.ControleProduto;
import Controle.ControleTipoProduto;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

public class AddNotaEntrada extends javax.swing.JFrame {
    ControleFornecedor fornecedor = null;
    ControleNota_entrada nota = null;
    ControleProduto produto = null;
    ControleTipoProduto tipoProd = null;
    CadTipoProduto tipoProduto = null;;
    ResultSet rsProduto = null;
    
    public AddNotaEntrada() {
        initComponents();
        this.setLocationRelativeTo(null);
        fornecedor = new ControleFornecedor();
        nota = new ControleNota_entrada();
        produto = new ControleProduto();
        tipoProd = new ControleTipoProduto();
        tipoProduto = new CadTipoProduto();
        
        rsProduto = tipoProd.consultar();
        
        try {
            while(rsProduto.next()){
                comboTIpoProd.addItem(rsProduto.getString("nome_tipo"));
            }
        } catch (SQLException ex) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProdutos = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomeProd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboTIpoProd = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtQntd = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDesc = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        btnCadastrarProduto = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        selectTpUnidade = new javax.swing.JComboBox<>();
        btnAddtipo = new javax.swing.JButton();
        txtValor_prod = new javax.swing.JFormattedTextField();
        buscarFornecedor = new javax.swing.JFrame();
        jLabel24 = new javax.swing.JLabel();
        txtPesquisarNome = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();
        btnSelecionar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtNomeForncedor = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtRazao = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtPesquisarCod = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtCodFornecedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboTipoEntrada = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaObs = new javax.swing.JTextArea();
        btnCadastrar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblDep = new javax.swing.JLabel();
        btnBuscarFornecedor = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtCodForn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNNota = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEmpenho = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        comboTpNota = new javax.swing.JComboBox<>();
        comboTpDoc = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboAlt = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValor_Nota = new javax.swing.JFormattedTextField();
        txtValor_alteracao = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        lblEx = new javax.swing.JLabel();

        addProdutos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addProdutos.setMinimumSize(new java.awt.Dimension(765, 460));

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome do produto", "Unidade", "Quantidade", "Valor Unitário", "Valor total"
            }
        ));
        jScrollPane2.setViewportView(tblProdutos);

        jLabel6.setText("Produtos:");

        jLabel7.setText("Nome do Produto:");

        jLabel8.setText("Tipo de Produto:");

        comboTIpoProd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboTIpoProdFocusGained(evt);
            }
        });
        comboTIpoProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboTIpoProdMouseClicked(evt);
            }
        });

        jLabel9.setText("Unidade:");

        jLabel10.setText("Quantidade:");

        jLabel22.setText("Valor Unitário:");

        txtAreaDesc.setColumns(20);
        txtAreaDesc.setRows(5);
        jScrollPane3.setViewportView(txtAreaDesc);

        jLabel23.setText("Descrição:");

        btnCadastrarProduto.setText("Cadastrar Produto");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        selectTpUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ml", "kg", "Unidade" }));
        selectTpUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTpUnidadeActionPerformed(evt);
            }
        });

        btnAddtipo.setText("+");
        btnAddtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtipoActionPerformed(evt);
            }
        });

        txtValor_prod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        javax.swing.GroupLayout addProdutosLayout = new javax.swing.GroupLayout(addProdutos.getContentPane());
        addProdutos.getContentPane().setLayout(addProdutosLayout);
        addProdutosLayout.setHorizontalGroup(
            addProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProdutosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addProdutosLayout.createSequentialGroup()
                        .addComponent(btnCadastrarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar))
                    .addComponent(jLabel6)
                    .addComponent(jLabel23)
                    .addGroup(addProdutosLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboTIpoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddtipo))
                            .addGroup(addProdutosLayout.createSequentialGroup()
                                .addComponent(selectTpUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQntd, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValor_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        addProdutosLayout.setVerticalGroup(
            addProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProdutosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(addProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(comboTIpoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddtipo))
                .addGap(18, 18, 18)
                .addGroup(addProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtQntd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(selectTpUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarProduto)
                    .addComponent(btnFinalizar))
                .addContainerGap())
        );

        buscarFornecedor.setMinimumSize(new java.awt.Dimension(700, 410));
        buscarFornecedor.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                buscarFornecedorWindowOpened(evt);
            }
        });

        jLabel24.setText("Pesquisar:");

        txtPesquisarNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisarNomeFocusLost(evt);
            }
        });
        txtPesquisarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarNomeKeyReleased(evt);
            }
        });

        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Razao Social", "CNPJ"
            }
        ));
        tblFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecedoresMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblFornecedoresMousePressed(evt);
            }
        });
        tblFornecedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblFornecedoresKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tblFornecedores);

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        jLabel25.setText("Nome:");

        txtNomeForncedor.setEditable(false);

        jLabel26.setText("Razão Social:");

        txtRazao.setEditable(false);

        jLabel27.setText("CNPJ:");

        txtCnpj.setEditable(false);

        jLabel28.setText("Por Nome:");

        jLabel29.setText("Por CNPJ:");

        txtPesquisarCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarCodKeyReleased(evt);
            }
        });

        jLabel30.setText("Código:");

        txtCodFornecedor.setEditable(false);

        javax.swing.GroupLayout buscarFornecedorLayout = new javax.swing.GroupLayout(buscarFornecedor.getContentPane());
        buscarFornecedor.getContentPane().setLayout(buscarFornecedorLayout);
        buscarFornecedorLayout.setHorizontalGroup(
            buscarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(buscarFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeForncedor, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buscarFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCnpj))
                    .addGroup(buscarFornecedorLayout.createSequentialGroup()
                        .addGroup(buscarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(btnSelecionar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(buscarFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarCod)))
                .addContainerGap())
        );
        buscarFornecedorLayout.setVerticalGroup(
            buscarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(buscarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(txtPesquisarCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buscarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtNomeForncedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(txtCodFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(buscarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnSelecionar)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedor");

        jLabel1.setText("Fornecedor:");

        jLabel2.setText("Ano:");

        jLabel11.setText("Tipo de Entrada:");

        comboTipoEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estoque", "Rotativa" }));

        jLabel12.setText("Observações:");

        txtAreaObs.setColumns(20);
        txtAreaObs.setRows(5);
        jScrollPane1.setViewportView(txtAreaObs);

        btnCadastrar.setText("Adicionar Produto(s)");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel13.setText("Dependencia:");

        lblDep.setText("Almoxarifado");

        btnBuscarFornecedor.setText("Buscar");
        btnBuscarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFornecedorActionPerformed(evt);
            }
        });

        jLabel14.setText("Código do Fornecedor:");

        txtCodForn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodFornKeyReleased(evt);
            }
        });

        jLabel15.setText("Série:");

        txtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerieActionPerformed(evt);
            }
        });

        jLabel16.setText("Nº da Nota:");

        txtNNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNNotaActionPerformed(evt);
            }
        });

        jLabel17.setText("Empenho:");

        txtEmpenho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpenhoActionPerformed(evt);
            }
        });

        jLabel18.setText("Data do Empenho:");

        jLabel19.setText("Tipo de Documento:");

        jLabel20.setText("Tipo de Nota:");

        comboTpNota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NF-e", "Nota de Serviço" }));

        comboTpDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nota Fiscal" }));

        jLabel5.setText("Alteração de Valor?:");

        comboAlt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Desconto", "Acrésimo" }));

        jLabel21.setText("Data de Emissão:");

        jLabel3.setText("Valor da Alteração:");

        jLabel4.setText("Valor da Nota");

        txtValor_Nota.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        txtValor_alteracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        txtValor_alteracao.setText("0");
        txtValor_alteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor_alteracaoActionPerformed(evt);
            }
        });

        jLabel31.setText("Exercício:");

        lblEx.setText("jLabel32");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(3, 3, 3)
                        .addComponent(txtCodForn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmpenho, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboTpNota, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboTipoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addGap(102, 102, 102)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValor_Nota))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboTpDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(102, 102, 102)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNNota, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDep)
                                .addGap(129, 129, 129)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEx))
                            .addComponent(jLabel12)
                            .addComponent(btnCadastrar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValor_alteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblDep)
                    .addComponent(jLabel31)
                    .addComponent(lblEx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarFornecedor)
                    .addComponent(jLabel14)
                    .addComponent(txtCodForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(txtNNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtEmpenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboTpDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtValor_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(comboTpNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(comboTipoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtValor_alteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void atualizaTabelaFornecedor(String pCampoNome, int pCampoCod ){        
        tblFornecedores.setModel(DbUtils.resultSetToTableModel(fornecedor.consultar(pCampoNome, pCampoCod)));
    }
    
    public void atualizaTabelaFornecedor(){        
        tblFornecedores.setModel(DbUtils.resultSetToTableModel(fornecedor.consultar()));
    }
    
    public void atualizaTabelaProdutos(){        
        tblProdutos.setModel(DbUtils.resultSetToTableModel(produto.consultar()));
    }
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String vNota = "", vAlt = "";
        
        if(txtCodForn.getText().equals("") || txtSerie.getText().equals("") || txtNNota.getText().equals("") || txtEmpenho.getText().equals("") || dataEmpenho.getDateFormatString().equals("") || dataEmissao.getDateFormatString().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha Corretamente os Campos !!", "Atenção", ERROR_MESSAGE);
        }else {
            nota.setFornecedor_cod(Integer.parseInt(txtCodForn.getText()));
            nota.setSecretaria_cod(lblDep.getText());
            nota.setExercicio(Integer.parseInt(lblEx.getText()));
            nota.setSituacao(1);
            nota.setAno(anoChosser.getYear());
            nota.setSerie(Integer.parseInt(txtSerie.getText()));
            nota.setN_nota(Integer.parseInt(txtNNota.getText()));
            nota.setEmpenho(Integer.parseInt(txtEmpenho.getText()));
            nota.setData_empenho(new Date(dataEmpenho.getDate().getTime()));
            nota.setData_entrada(produto.getDateTime());
            nota.setTp_doc(comboTpDoc.getSelectedItem().toString());
            nota.setTp_nota(comboTpNota.getSelectedItem().toString());
            nota.setData_emissao(new Date(dataEmissao.getDate().getTime()));
            nota.setDescricao(txtAreaObs.getText());
            nota.setTp_entrada(comboTipoEntrada.getSelectedItem().toString());
            nota.setAlteracao_valor(comboAlt.getSelectedItem().toString());


            vNota = txtValor_Nota.getText().replace(".", "").replace(",", ".");
            nota.setValor_nota(Double.parseDouble(vNota));

            vAlt = txtValor_alteracao.getText().replace(".", "").replace(",", ".");
            nota.setValor_alteracao(Double.parseDouble(vAlt));
        
            if(nota.cadastrar()){
                
                JOptionPane.showMessageDialog(null, "Adicionar os Produtos !!");
                addProdutos.setEnabled(true);
                addProdutos.setVisible(true);

            }else {
                JOptionPane.showMessageDialog(null, "Erro ao adicionar Nota", "erro", ERROR_MESSAGE);
            }  
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerieActionPerformed

    private void txtNNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNNotaActionPerformed

    private void txtEmpenhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpenhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpenhoActionPerformed

    private void txtPesquisarNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarNomeKeyReleased
        atualizaTabelaFornecedor(txtPesquisarNome.getText(), 0);
    }//GEN-LAST:event_txtPesquisarNomeKeyReleased

    private void txtPesquisarCodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarCodKeyReleased
        if(txtPesquisarCod.getText().equals("")){
            atualizaTabelaFornecedor();
        }else {
            atualizaTabelaFornecedor("", Integer.parseInt(txtPesquisarCod.getText()));
        }
    }//GEN-LAST:event_txtPesquisarCodKeyReleased

    private void tblFornecedoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblFornecedoresKeyReleased
        txtCodFornecedor.setText(tblFornecedores.getModel().getValueAt(tblFornecedores.getSelectedRow(),0).toString());
        txtNomeForncedor.setText(tblFornecedores.getModel().getValueAt(tblFornecedores.getSelectedRow(),1).toString());
        txtRazao.setText(tblFornecedores.getModel().getValueAt(tblFornecedores.getSelectedRow(),2).toString());
        txtCnpj.setText(tblFornecedores.getModel().getValueAt(tblFornecedores.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tblFornecedoresKeyReleased

    private void tblFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedoresMouseClicked
        
    }//GEN-LAST:event_tblFornecedoresMouseClicked

    private void btnBuscarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFornecedorActionPerformed
        buscarFornecedor.setVisible(true);
        buscarFornecedor.setEnabled(true);
        atualizaTabelaFornecedor();
    }//GEN-LAST:event_btnBuscarFornecedorActionPerformed

    private void buscarFornecedorWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_buscarFornecedorWindowOpened
        atualizaTabelaFornecedor();
    }//GEN-LAST:event_buscarFornecedorWindowOpened

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        txtCodForn.setText(txtCodFornecedor.getText());
        txtFornecedor.setText(txtNomeForncedor.getText());
        
        buscarFornecedor.setVisible(false);
        buscarFornecedor.setEnabled(false);
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void txtPesquisarNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarNomeFocusLost
        
    }//GEN-LAST:event_txtPesquisarNomeFocusLost

    private void tblFornecedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedoresMousePressed
        txtCodFornecedor.setText(tblFornecedores.getModel().getValueAt(tblFornecedores.getSelectedRow(),0).toString());
        txtNomeForncedor.setText(tblFornecedores.getModel().getValueAt(tblFornecedores.getSelectedRow(),1).toString());
        txtRazao.setText(tblFornecedores.getModel().getValueAt(tblFornecedores.getSelectedRow(),2).toString());
        txtCnpj.setText(tblFornecedores.getModel().getValueAt(tblFornecedores.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tblFornecedoresMousePressed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        String i = "";
        addProdutos.dispose();
        
        txtCodForn.setText(i);
        txtFornecedor.setText(i);
        txtAreaDesc.setText(i);
        txtAreaObs.setText(i);
        txtEmpenho.setText(i);
        txtNNota.setText(i);
        txtCodFornecedor.setText(i);
        txtNomeForncedor.setText(i);
        txtNomeProd.setText(i);
        txtPesquisarCod.setText(i);
        txtPesquisarNome.setText(i);
        txtQntd.setText(i);
        txtRazao.setText(i);
        txtSerie.setText(i);
        txtValor_Nota.setText(i);
        txtValor_alteracao.setText("0,00");
        txtValor_prod.setText(i);
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void selectTpUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTpUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTpUnidadeActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        String valorUni = "";

        if(txtNomeProd.getText().equals("") || txtQntd.getText().equals("") || txtValor_prod.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha Corretamente os Campos !!", "Atenção", ERROR_MESSAGE);
        }else{

            produto.setNota_entrada_fk();
            produto.setNome(txtNomeProd.getText());
            produto.setTpProdutos_cod(comboTIpoProd.getSelectedItem().toString());
            produto.setUnidade(selectTpUnidade.getSelectedItem().toString());
            produto.setQntd(Integer.parseInt(txtQntd.getText()));

            valorUni = txtValor_prod.getText().replace(".", "").replace(",", ".");
            produto.setValor_uni(Double.parseDouble(valorUni));
            produto.setValor_total();
            produto.setDescricao(txtAreaDesc.getText());

            if(produto.cadastrar()){
                JOptionPane.showMessageDialog(null, "Produto "+txtNomeProd.getText()+" Adicionado a Nota:"+txtNNota.getText());
                atualizaTabelaProdutos();
                limparCamposTelaProduto();
            }else {
                JOptionPane.showMessageDialog(null, "Erro ao adicionar produto, contato o suporte do sistema", "Atenção", ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void btnAddtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtipoActionPerformed
        tipoProduto.setEnabled(true);
        tipoProduto.setVisible(true);
        
        
    }//GEN-LAST:event_btnAddtipoActionPerformed

    private void comboTIpoProdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboTIpoProdFocusGained
        comboTIpoProd.removeAllItems();
        rsProduto = tipoProd.consultar();
        
        try {
            while(rsProduto.next()){
                comboTIpoProd.addItem(rsProduto.getString("nome_tipo"));
            }
        } catch (SQLException ex) {}
    }//GEN-LAST:event_comboTIpoProdFocusGained

    private void comboTIpoProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTIpoProdMouseClicked
        comboTIpoProd.removeAllItems();
        rsProduto = tipoProd.consultar();
        
        try {
            while(rsProduto.next()){
                comboTIpoProd.addItem(rsProduto.getString("nome_tipo"));
            }
        } catch (SQLException ex) {}
    }//GEN-LAST:event_comboTIpoProdMouseClicked

    private void txtCodFornKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodFornKeyReleased
        if(txtCodForn.getText().equals("")){
            txtFornecedor.setText("");
        }else {
            txtFornecedor.setText(fornecedor.consultarNomeFornecedor(Integer.parseInt(txtCodForn.getText())));
        }
    }//GEN-LAST:event_txtCodFornKeyReleased

    private void txtValor_alteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor_alteracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor_alteracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNotaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNotaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNotaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNotaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNotaEntrada().setVisible(true);
            }
        });
    }
    
    public void limparCamposTelaProduto(){
        txtNomeProd.setText("");
        txtQntd.setText("");
        txtValor_prod.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame addProdutos;
    private javax.swing.JButton btnAddtipo;
    private javax.swing.JButton btnBuscarFornecedor;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JFrame buscarFornecedor;
    private javax.swing.JComboBox<String> comboAlt;
    private javax.swing.JComboBox<String> comboTIpoProd;
    private javax.swing.JComboBox<String> comboTipoEntrada;
    private javax.swing.JComboBox<String> comboTpDoc;
    private javax.swing.JComboBox<String> comboTpNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblDep;
    private javax.swing.JLabel lblEx;
    private javax.swing.JComboBox<String> selectTpUnidade;
    private javax.swing.JTable tblFornecedores;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextArea txtAreaDesc;
    private javax.swing.JTextArea txtAreaObs;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtCodForn;
    private javax.swing.JTextField txtCodFornecedor;
    private javax.swing.JTextField txtEmpenho;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtNNota;
    private javax.swing.JTextField txtNomeForncedor;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtPesquisarCod;
    private javax.swing.JTextField txtPesquisarNome;
    private javax.swing.JTextField txtQntd;
    private javax.swing.JTextField txtRazao;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JFormattedTextField txtValor_Nota;
    private javax.swing.JFormattedTextField txtValor_alteracao;
    private javax.swing.JFormattedTextField txtValor_prod;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getLblDep() {
        return lblDep;
    }

    public void setLblDep(javax.swing.JLabel lblDep) {
        this.lblDep = lblDep;
    }

    public javax.swing.JLabel getLblEx() {
        return lblEx;
    }

    public void setLblEx(javax.swing.JLabel lblEx) {
        this.lblEx = lblEx;
    }
}
